name: e_commerce
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.3
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+15
  path: ^1.7.0
  firebase_storage: ^4.0.0
  image_downloader: ^0.20.1
  splashscreen: ^1.3.5
  font_awesome_flutter: ^8.11.0
  circular_check_box: ^1.0.2
  flutter_native_splash: ^0.2.7
  basic_utils: ^1.2.0
  text_tools: ^0.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/man/
    - images/woman/
    - images/kids/
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Medium.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    - family: Karla
      fonts:
        - asset: fonts/Karla-Medium.ttf

